=== silviaDeyanova/XML-Project/museums.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT museum_cataloque (museum+)>
<!ELEMENT museum (name, description, ticket_options, visiting_hours, address, images)>
<!ATTLIST museum id ID #REQUIRED>
<!ATTLIST museum region CDATA #REQUIRED>
<!ATTLIST museum url CDATA #IMPLIED>
<!ELEMENT name (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT ticket_options (ticket+)>
<!ELEMENT ticket (type,price)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT visiting_hours (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT images (image+)>
<!ELEMENT image EMPTY>
<!ATTLIST image href ENTITY #REQUIRED>
<!NOTATION jpg PUBLIC "jpg viewer">

=== silviaDeyanova/XML-Project/xmlProject.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE museum_cataloque SYSTEM "museums.dtd"[
<!ENTITY NationalHistorical1 SYSTEM "images/НАЦИОНАЛЕНИСТОРИЧЕСКИМУЗЕЙ_1.jpg" NDATA jpg>
<!ENTITY NationalHistorical2 SYSTEM "images/НАЦИОНАЛЕНИСТОРИЧЕСКИМУЗЕЙ_2.jpg" NDATA jpg>
<!ENTITY EarthAndPeople1 SYSTEM "images/НАЦИОНАЛЕНМУЗЕЙЗЕМЯТАИХОРАТАСОФИЯ_1.jpg" NDATA jpg>
<!ENTITY EarthAndPeople2 SYSTEM "images/НАЦИОНАЛЕНМУЗЕЙЗЕМЯТАИХОРАТАСОФИЯ_2.jpg" NDATA jpg>
<!ENTITY EarthAndPeople3 SYSTEM "images/НАЦИОНАЛЕНМУЗЕЙЗЕМЯТАИХОРАТАСОФИЯ_3.jpg" NDATA jpg>
<!ENTITY MilitaryHistorical1 SYSTEM "images/НАЦИОНАЛЕНВОЕННОИСТОРИЧЕСКИМУЗЕЙСОФИЯ_1.jpg" NDATA jpg>
<!ENTITY MilitaryHistorical2 SYSTEM "images/НАЦИОНАЛЕНВОЕННОИСТОРИЧЕСКИМУЗЕЙСОФИЯ_2.jpg" NDATA jpg>
<!ENTITY NationalArcheological1 SYSTEM "images/НАЦИОНАЛЕНАРХЕОЛОГИЧЕСКИМУЗЕЙСОФИЯ_1.jpg" NDATA jpg>
<!ENTITY NationalArcheological2 SYSTEM "images/НАЦИОНАЛЕНАРХЕОЛОГИЧЕСКИМУЗЕЙСОФИЯ_2.jpg" NDATA jpg>
<!ENTITY NationalArcheological3 SYSTEM "images/НАЦИОНАЛЕНАРХЕОЛОГИЧЕСКИМУЗЕЙСОФИЯ_3.jpg" NDATA jpg>
<!ENTITY RegionalArcheological1 SYSTEM "images/РЕГИОНАЛЕНАРХЕОЛОГИЧЕСКИМУЗЕЙГРАДПЛОВДИВ_1.jpg" NDATA jpg>
<!ENTITY RegionalArcheological2 SYSTEM "images/РЕГИОНАЛЕНАРХЕОЛОГИЧЕСКИМУЗЕЙГРАДПЛОВДИВ_2.jpg" NDATA jpg>
<!ENTITY Archeological1 SYSTEM "images/АРХЕОЛОГИЧЕСКИМУЗЕЙГРАДСАНДАНСКИ_1.jpg" NDATA jpg>
<!ENTITY Archeological2 SYSTEM "images/АРХЕОЛОГИЧЕСКИМУЗЕЙГРАДСАНДАНСКИ_2.jpg" NDATA jpg>
<!ENTITY Figures1 SYSTEM "images/МУЗЕЙНАВОСЪЧНИТЕФИГУРИГРАДВЕЛИКОТЪРНОВО_1.jpg" NDATA jpg>
<!ENTITY Figures2 SYSTEM "images/МУЗЕЙНАВОСЪЧНИТЕФИГУРИГРАДВЕЛИКОТЪРНОВО_2.jpg" NDATA jpg>
<!ENTITY Humour1 SYSTEM "images/МУЗЕЙДОМНАХУМОРАИСАТИРАТАГРАДГАБРОВО_1.jpg" NDATA jpg>
<!ENTITY Humour2 SYSTEM "images/МУЗЕЙДОМНАХУМОРАИСАТИРАТАГРАДГАБРОВО_2.jpg" NDATA jpg>
<!ENTITY Humour3 SYSTEM "images/МУЗЕЙДОМНАХУМОРАИСАТИРАТАГРАДГАБРОВО_3.jpg" NDATA jpg>
<!ENTITY Wine1 SYSTEM "images/МУЗЕЙНАВИНОТОГРАДМЕЛНИК_1.jpg" NDATA jpg>
<!ENTITY Wine2 SYSTEM "images/МУЗЕЙНАВИНОТОГРАДМЕЛНИК_2.jpg" NDATA jpg>
<!ENTITY Wine3 SYSTEM "images/МУЗЕЙНАВИНОТОГРАДМЕЛНИК_3.jpg" NDATA jpg>
<!ENTITY Wine4 SYSTEM "images/МУЗЕЙНАВИНОТОГРАДМЕЛНИК_4.jpg" NDATA jpg>
<!ENTITY Military1 SYSTEM "images/ВОЕННОИСТОРИЧЕСКИМУЗЕИГРАДПЛЕВЕН_1.jpg" NDATA jpg>
<!ENTITY Military2 SYSTEM "images/ВОЕННОИСТОРИЧЕСКИМУЗЕИГРАДПЛЕВЕН_2.jpg" NDATA jpg>
]>
<museum_cataloque>
    <museum id = "m1" region = "София" url = "">
        <name>Национален Исторически музей</name>
        <description>
        Националният исторически музей е създаден на 5 май 1973 г. 
        Той е национална съкровищница на Република България, хранилище на реликви от световен мащаб и един от най-големите исторически музеи на Балканския полуостров.
        В него се съхраняват над 650 000 паметници на културата и огромен археологически и исторически архив.
        Националният исторически музей e eдин от най-големите и богати исторически музеи на Балканския полуостров.
        В него се съхраняват над 700 000 паметници на културата, представящи историята на днешните български земи отпреди 8000 години до наши дни. 
        В залите на музея са изложени едва 10% от всички тези ценности и паметници.
        В двора на музея има богата колекция от каменни колони, паметници от различни периоди – гръцки, римски, византийски.
        </description>
        <ticket_options>
            <ticket>
                <type>входeн билет за индивидуалeн посетител</type>
                <price>10.00 лв.</price>
            </ticket>
            <ticket>
                <type>за ученици и студенти</type>
                <price>2.00 лв.</price>
            </ticket>
            <ticket>
                <type>за посетители, придружени от деца</type>
                <price>4.00 лв.</price>
            </ticket>
            <ticket>
                <type>за децата над 7 години</type>
                <price>2.00 лв.</price>
            </ticket>
        </ticket_options>
        <visiting_hours>9:30 – 18:00 ч.</visiting_hours>
        <address>
        Национален исторически музей
        ул. "Витошко лале" 16
        София 1618
        България
        </address>
        <images>
            <image href="NationalHistorical1" />
            <image href="NationalHistorical2" />
        </images>
    </museum>

    <museum id = "m2" region = "София" url = "">
        <name>Национален музей „Земята и хората“</name>
        <description>
            Националният музей „Земята и хората”- София е държавен културен институт с национално значение.
            Извършва общонационални функции по издирване, придобиване, изучаване, опазване и представяне на минералите и минералните ресурси,
            като важна част от националното природно наследство.Сградата на Националния музей „Земята и хората” е построена в края на ХІХ век,
            като най-голямата постройка от тогавашната военна работилница . Една от първите сгради с цялостна железобетонна конструкция.
            Обявена е за недвижима културна ценност. През 1986 г. е предоставена безвъзмездно за изграждане на музей „Земята и хората”.
            Музеят притежава богати и добре комплектувани фондове. Към януари 2021 г. има над 32 662 музейни единици.
            Всички материали са систематизирани в 7 раздела. Разделът "Минерални ресурси на България" съхранява образци от около 400 български находища
            и рудопроявления. Най-атрактивната част в музея е експозицията „Гигантски кристали “ - една от двете големи експозиции в света;
            „Минерали на Земята“ е най-богатата систематична колекция на Балканите, включваща над  7700 образеца от 1663 минерални вида, 
            при общо известни за науката 5200. "Минерали на България" най-пълната колекция от български минерали (326 вида), представени в над 4600 бр. 
            минерални образци. "Скъпоценни и декоративни камъни" има близо 3000  образеца от всички видове скъпоценни камъни.
        </description>
        <ticket_options>
            <ticket>
                <type>Индивидуални посетители</type>
                <price>6.00 лв.</price>
            </ticket>
            <ticket>
                <type>Ученици, студенти и пенсионери</type>
                <price>3.00 лв.</price>
            </ticket>
            <ticket>
                <type>Образователен кът за деца и възрастни</type>
                <price>1.00 лв.</price>
            </ticket>
        </ticket_options>
        <visiting_hours>08.30 - 17.00 ч.</visiting_hours>
        <address>
            гр. София 1421
            бул. "Черни връх" № 4
            Национален музей “Земята и хората“
        </address>
        <images>
            <image href="EarthAndPeople1" />
            <image href="EarthAndPeople2" />
            <image href="EarthAndPeople3" />
        </images>
    </museum>

    <museum id = "m3" region = "София" url = "">
        <name>Национален военноисторически музей</name>
        <description>
                    Военният музей е третата общонационална музейна структура след разделянето през 1906 г. на първия български Народен музей
                    на два музея – Археологически и Етнографски.Първата експозиция на Главния Военен музей е открита едва на 12 май 1937 г. на ул. Московска № 15,
                    в сграда, отдадена му под наем от Софийското офицерско събрание. През 1949 г. музеят е преименуван в Централен музей на народната армия.
                    През 1950–1951 г. Музеят е преместен на бул. “Ген. Скобелев № 23”, където през 1952 г. открива нова експозиция.
                    През 1956 г. филиал на музея става Военноморският музей в гр. Варна. Същата година започва работа първото реставрационно ателие.
                    След спогодба между правителствата на България и Унгария, през 1967 г. колективът на Военния музей създава единствения в чужбина
                    Музей на Първа българска армия. Негови филиали стават Военноморският музей и Парк-музеят на бойната дружба Владислав Варненчик в гр. Варна.
                    За своето вековно присъствие в културноисторическото пространство в неговите фондове са съхранени и проучени повече от 1 000 000 културни ценности,
                    свидетели на българската и европейска военна история.
        </description>
        <ticket_options>
            <ticket>
                <type>Ученици, студенти, пенсионери и хора с увреждания</type>
                <price>	2 лв.</price>
            </ticket>
            <ticket>
                <type>Възрастни</type>
                <price> 8 лв.</price>
            </ticket>
            <ticket>
                <type>Посещение на колекционните зали</type>
                <price>	4 лв.</price>
            </ticket>
            <ticket>
                <type>Посещение на временните изложби</type>
                <price>	4 лв.</price>
            </ticket>
            <ticket>
                <type>Семеен билет (колекционни зали и временни изложби)</type>
                <price>	10 лв.</price>
            </ticket>
            <ticket>
                <type>Семеен билет (колекционни зали)</type>
                <price>	6 лв.</price>
            </ticket>
            <ticket>
                <type>Семеен билет (временни изложби)</type>
                <price>	6 лв.</price>
            </ticket>
            <ticket>
                <type>Посещение на временните изложби</type>
                <price>	4 лв.</price>
            </ticket>
            <ticket>
                <type>Деца (до 7 г.)</type>
                <price>	Безплатно</price>
            </ticket>
        </ticket_options>
        <visiting_hours>сряда – неделя: 10.00 – 18.00 ч.</visiting_hours>
        <address>
                    България, 1505, гр. София
                    ул. „Черковна“ No 92
        </address>
        <images>
